### ISSUE TITLE
Ignore message, not our networkID.

### ISSUE THREAD

**Issue by mustberain** [arnemauer/Ducobox-ESPEasy-Plugin#21]
Hi,

How can I figure out the networkID for the ducobox? Everything seems to work except controlling the duco because of this message. See part of log:

503445: [P150] DUCO RF GW: Received message: RSSI:179; SRC:2; DEST:0; ORG.SRC:1; ORG.DEST:0; Ntwrk:000726f9; Type:7; Bytes:15; Cntr:15;
503446: [P150] DUCO RF GW: 50,20,00,52,00,E3,B3,
503446: [P150] DUCO RF GW: Ignore message, not our networkID.

This is after I joined and sent a command like VENTMODE, HIGH, 100%

**Comment by arnemauer** [comment]
This message is not related to controlling your Ducobox. After a succesfull join you can find the network ID of your ducobox on the RF plugin page. 

![RF plugin task settings](https://raw.githubusercontent.com/arnemauer/Ducobox-ESPEasy-Plugin/master/Screenshots/Configureren%20RF%20gateway%20-%20join%20succes.png)

The plugin will ignore messages from other network ID's. Otherwise, your gateway will process the commands from the ducobox of your neighbors ;)
