### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by arcangel321** [arnemauer/Ducobox-ESPEasy-Plugin#65]
I got an memory error.
![D9704C2D-1285-4E21-BD39-5EF20928F844](https://user-images.githubusercontent.com/50084706/104508943-477c4700-55e9-11eb-9806-221c984503a8.jpeg)

setup:
Home assistant 
MQTT
Ventilation gateway 
Latest firmware

How can we solve this?

**Comment by arnemauer** [comment]
Fixt een reboot het probleem? 
Wanneer treed het probleem op?

**Comment by arcangel321** [comment]
Het apparaat reboot al elke dag om vast lopers te voorkomen. Het probleem treed op bij het openen van de webpagina.

Zover ik kan zien staat debug uit.

**Comment by mpepping** [comment]
Same here. The memory error occurs after a couple of weeks without rebooting. The strange thing is that this is happening only since the past months, without any changes to the firmware. Maybe something changed on the MQTT broker side (Mosquitto via HA add-on) that affects the gateway. Can't really think of anything else.

Anyway, after a reboot, all memory thresholds seem quite OK:

```
Free Mem:            | 3992 (25160 - )
Free Stack:          | 3664 (3824 - )
Heap Max Free Block: | 2936
Heap Fragmentation:  |  25%
```

**Comment by arnemauer** [comment]
Fixed :)
